### ISSUE TITLE
VnV plan document is ready for review

### ISSUE THREAD

**Issue by JohnErnsthausen** [JohnErnsthausen/roc#10]
Hello, Leila @LeilaMousapour and Prof. Smith @smiths. My VnV Plan document is ready for review.

**Comment by smiths** [comment]
Spelling corrections made in 65fd3da.

@JohnErnsthausen, in the future, please assign the issues to each reviewer separately, so that they can close the issue when they have completed the task.

**Comment by smiths** [comment]
Feedback on VnV Plan available in 5c39c80.

**Comment by JohnErnsthausen** [comment]
Thank you.
