### ISSUE TITLE
Implementation Verification Plan section is not comprehensive

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#11]
Hi @JohnErnsthausen ,
I hope you are well! I am gaining to mention several issues I noticed in your VnV plan document. I hope they are relevant and helpful!
 
In the “Implementation Verification Plan” part, you only focused at “unit testing” and based on my understanding, you covered what should be explained in the “unit VnV plan”.  I believe this session should give an overview of all sort of dynamic and static testing strategies that you use for -system- verification, as well as -unit- verification plans. For example, you use "parallel testing" for system verification but you are not mentioning it. 
Also, I think you might benefit from other testing strategies such as “interval arithmetic testing” and “comparison with closed-form solution”.

Additionally, another point here is the sentence “The code should be well formatted and free of memory leaks.” I think the point of VnV plan is to specify "how" you are going to achieve this, which you tell in the next part of the doc; But maybe for the sake of cohesiveness, talk about them in the same paragraph.

**Comment by JohnErnsthausen** [comment]
Hello @LeilaMousapour,

Your advice is well received. I truly appreciate your time and effort. I updated my "Implementation Verification Plan" section. Clearly it needs more work, but this is a start to get a handle on issues and feedback.

[commit d20486](https://github.com/JohnErnsthausen/roc/commit/d20486e416bee1f418b945d86a01681110704618)

@smiths
