### ISSUE TITLE
Test case outputs

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#12]
Hi @JohnErnsthausen,

In your test cases, in the "output" part, you need to specify what the output for the given input is. However, you have stated "the difference between the answer of your software and the pseudo-oracle" is the output while it is the measure which we judge the test based on and it is not the output and us related to the "How test will be performed:" section.

Also, in the "Test Case Derivation" you need to explain why the output of your software to the inputs should the the outputs; while you have explained the reason you have chosen the test case.

Additionally, I believe the sentence "Compare the results. Expect the results to compare within 10%." should go under the "How test will be performed:" section.

**Comment by JohnErnsthausen** [comment]
Hello @LeilaMousapour and Prof @smiths,

Thank you for your comments.

I have carefully considered these remarks. I believe these tests are correct as written.
