### ISSUE TITLE
Software Validation Plan

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#13]
Hi @JohnErnsthausen,

The "validation" is done when we have data from a real world experiment and we want to see if the way that we are modelling the problem is actually correct and the equations and assumptions are applicable to that problem. However, in your case I believe you don't have that kind of data as you are not modelling a physical problem and you are solving a math equation; Thus "validation" is not applicable to your project. 
I believe what you explained under this section is the parallel testing explanation for the system verification, so you might want to move it to the section 4.4.

**Comment by JohnErnsthausen** [comment]
Thank you for your comment @LeilaMousapour. I believe you have learned a lot in our class.

I responded to your comment by updating my VnVPlan.

[commit 1e1ed2](https://github.com/JohnErnsthausen/roc/commit/1e1ed2eb361a0b872a03b45aceb0b3c81b0341d8)

@smiths
