### ISSUE TITLE
Missing traceability matrix 

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#14]
Hi @JohnErnsthausen,

the traceability section lack a table that traces which test case is supporting which requirement. Although it is stated that this has been specified while explaining each test case, I believe in terms of documentation, following the template and including a table would make future reference easier. Let’s say a third party person is only interested in testing the R3 and they are looking for the test case. The table helps them find it way easier rather than skimming through the whole VnV doc.

**Comment by JohnErnsthausen** [comment]
Hello @LeilaMousapour and Prof @smiths,

I hear you Leila on this issue and strictly speaking you are correct for this course.

However I would find a traceability table difficult to present as I have 158 tests, difficult to maintain, and a duplication of work. I wouldn't find this table useful. Here's why.

In the Module Guide there is "Table 2: Trace Between Requirements and Modules". Here I'm thinking of Module as a Parnas Module, a work order. For every work order, I Test Drive the behavior given in the work order into my code base. All of the behaviors required by the module must have corresponding testing code. I then do code coverage on my tests. If I have 100% code coverage of my tests and all the required behaviors are covered in the module. Then by my testing, I automatically have the functionality of the traceability table in discussion making the traceability table unnecessary work.

The Software Development theories of Test Driving recommend running all test and observing that all tests pass. The interest of the third party in "Let’s say a third party person is only interested in testing the R3" should be highly discouraged.

[Commit b193ad](https://github.com/JohnErnsthausen/roc/commit/b193ad480d34b51f53f84b3fbaba1d167f1dedf6)
