### ISSUE TITLE
R4 is not tested

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#15]
Hi @JohnErnsthausen,

I believe the R4 which is about overestimating the ROC, is a very important requirement. Do you address this in assumptions or how would you test if your software is not doing so?

**Comment by JohnErnsthausen** [comment]
Hello @LeilaMousapour and @smiths,

Truly. R4 is a very important requirement.

For real power series, power series where the coefficients and expansion point is real, theory says there can only be poles, logarithmic branch points, and essential singularities on the real axis or in conjugate pairs. The power series we consider are (truncated) real power series.

ROC can distinguish poles and estimate the tail of the error verifying Assumption 1. ROC cannot distinguish logarithmic branch points and essential singularities yet. Specifically ROC fits the given list of truncated coefficients to three patterns. The pattern of one real pole (ThreeTermAnalysis or 3TA) and a pair of complex conjugate poles (SixTermAnalysis or 6TA) can be distinguished in the case of primary singularities. When there are secondary singularities, ROC uses Top Line Analysis (TLA). The case of entire functions is not considered in ROC yet.

The test results I include in this response, from running tests in the test directory, demonstrate that the algorithms I apply in ROC resolve the singularities they are designed to resolve. This statement is not exhaustive nor a proof. In theory, ROC will resolve an arbitrary truncated series of a (non entire) function whose primary singularity is near a pole. If the summed term by term difference between the model problem (3TA or 6TA) is small, then ROC provides an accurate estimate of the ROC and the estimate is not an overestimate. The TLA is a conservative estimate and I don't have mathematical assurances that the TLA estimate will not be an over estimate. However, ROC accounts for the ad hoc nature of the analysis through an engineering safty factor by taking .6 of the recommended ROC.

[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtZeroWithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtZeroWithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtPT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtPT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtZeroWithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtZeroWithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtPT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] SixTermAnalysisOf.TaylorSeriesAtPT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingHundredthForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingHundredthForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtZeroWithScalingThousandthForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtZeroWithScalingThousandthForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtPT3WithScalingThousandthForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtPT3WithScalingThousandthForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtNegativePT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtZeroWithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtZeroWithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtPT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree
[       OK ] SixTermAnalysisOf.TaylorSeriesAtPT3WithoutScalingForComplexConjugatePolesAtPMOneFifthAlphaThree (0 ms)
[ RUN      ] SixTermAnalysisOf.TaylorSeriesAtNegativeOneNearARealPoleAtOneWithScalingTenthAlphaOneExpectedToFail
[       OK ] SixTermAnalysisOf.TaylorSeriesAtNegativeOneNearARealPoleAtOneWithScalingTenthAlphaOneExpectedToFail (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOneRealPoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOneRealPoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtZeroOneRealPoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtZeroOneRealPoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtPTNineOneRealPoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtPTNineOneRealPoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT0001RealPoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT0001RealPoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT9RealPoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT9RealPoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtThreePoleAtOneWithScalingTenthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtThreePoleAtOneWithScalingTenthAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOneRealPoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOneRealPoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtZeroOneRealPoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtZeroOneRealPoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtPTNineOneRealPoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtPTNineOneRealPoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT0001RealPoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT0001RealPoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT9RealPoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtOnePT9RealPoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtThreePoleAtOneWithScalingOneAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtThreePoleAtOneWithScalingOneAlphaOne (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOnePoleAtOneWithScalingTenthAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOnePoleAtOneWithScalingTenthAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtZeroPoleAtOneWithScalingTenthAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtZeroPoleAtOneWithScalingTenthAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtPT9PoleAtOneWithScalingTenthAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtPT9PoleAtOneWithScalingTenthAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOnePoleAtOneWithScalingOneAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtNegativeOnePoleAtOneWithScalingOneAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtZeroPoleAtOneWithScalingOneAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtZeroPoleAtOneWithScalingOneAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtPT9PoleAtOneWithScalingOneAlphaTwo
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtPT9PoleAtOneWithScalingOneAlphaTwo (0 ms)
[ RUN      ] ThreeTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne
[       OK ] ThreeTermAnalysisOf.TaylorSeriesAtNegativePT3WithScalingTenthForComplexConjugatePolesAtPMOneFifthAlphaOne (0 ms)
[ RUN      ] TestThatTopLine.WillComputeLeastSquarsSolution
[       OK ] TestThatTopLine.WillComputeLeastSquarsSolution (0 ms)
