### ISSUE TITLE
Discuss MIS

### ISSUE THREAD

**Issue by JohnErnsthausen** [JohnErnsthausen/roc#19]
Dear Prof Smith,

Would you have an appointment time available? I'm royalty confused about MIS goals and content as it applies to ROC.

Thank you,
John

@smiths

**Comment by smiths** [comment]
Hello John.  My schedule is available at:

http://www.cas.mcmaster.ca/~smiths/SSmithSchedule.html

Please suggest a time that works for you.

Best wishes.

_________________________________

Spencer Smith, PhD, PEng
Associate Professor
Department of Computing and Software
McMaster University

Tel: (905) 525-9140 X27929
Room: ITB/167
Web: http://www.cas.mcmaster.ca/~smiths
_________________________________

**Comment by JohnErnsthausen** [comment]
Hi @smiths, I'd like to schedule Thursday at 1. Good?

**Comment by smiths** [comment]
Hello John.  Yes, the proposed time sounds fine.  I will call you on Teams.

Best wishes.

_________________________________

Spencer Smith, PhD, PEng
Associate Professor
Department of Computing and Software
McMaster University

Tel: (905) 525-9140 X27929
Room: ITB/167
Web: http://www.cas.mcmaster.ca/~smiths
_________________________________

**Comment by JohnErnsthausen** [comment]
I appreciate our conversation today, Prof @smiths. Thank you.

I forgot to ask: On p. 12 of SRS_Fdbck.pdf, your comment says to "Have a look at the rational I added to the blank project template on non-functional requirements." I did this, but I don't see what was added to the blank project template. Please clarify this comment.

**Comment by smiths** [comment]
Hello @JohnErnsthausen.  The additions I made to the SRS about NFRs are from this commit:

https://gitlab.cas.mcmaster.ca/smiths/cas741/-/commit/005652db1c9c34b8dda67ab9df9ba96f6cc0fa3e

**Comment by JohnErnsthausen** [comment]
Thank you, @smiths .
