### ISSUE TITLE
MG review - tiny template issues

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#24]
Hi John @JohnErnsthausen ,

1- In MG section 2, reference material, Explanation of program name is not given appropriately. 
2- In MG, I believe the revision history is not updated as the first version was submitted on Nov 22nd and the version I am reviewing has been submitted on Dec 4th.

**Comment by JohnErnsthausen** [comment]
Thank you @LeilaMousapour and Prof @smiths,

Update in [Commit 897399](https://github.com/JohnErnsthausen/roc/commit/897399006de51f4375487da967f5a4952784e0ff)
