### ISSUE TITLE
MG review - anticipated changes are not clear

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#25]
Hi John @JohnErnsthausen,

The way you have phrased the anticipated changes can be improved. I believe the AC should be more like a "noun". For instance, AC1 could be: handling the input or being more -specific- about what can change in the way you handle the input, e.g. the format or the way you ask the user to input the data.

Also, AC4 is not specific at all. Generally, the ACs should be specific enough so that they can be mapped to a certain module.
For AC5-8, again the phrasing can be improved. As a reader, after reading AC5, I would ask “what exactly would change? Is it the algorithm for finding this distance that would change or what?”

AC7 does not sound like an anticipated change; it is more like a future challenge.

**Comment by JohnErnsthausen** [comment]
Dear @LeilaMousapour and Prof @smiths,

Thank you for your comments Leila. You learned a lot in this course.

I addressed your concerns in [Commit cb9f78](https://github.com/JohnErnsthausen/roc/commit/cb9f785cc9caf25a90c85c4ffe50214048fa17a1).
