### ISSUE TITLE
MG review - M1 and M2 module category 

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#26]
Hi John @JohnErnsthausen ;

The Inout format module (M1) and the output format module (M2) are listed 2 times under both “hardware hiding modules” and “behaviour hiding module”.  These 2 module are actually only behaviour hiding modules.

**Comment by JohnErnsthausen** [comment]
Dear @LeilaMousapour and Prof @smiths,

Thank you for your comments Leila.

I addressed your concerns in [Commit be91b6](https://github.com/JohnErnsthausen/roc/commit/be91b6f46a3965e2e03542193e0b64a3b980cada).
