### ISSUE TITLE
MG review - Hardware hiding module

### ISSUE THREAD

**Issue by LeilaMousapour** [JohnErnsthausen/roc#27]
Hi John @JohnErnsthausen;

In the case of your software, there is only one hardware hiding module which is implemented by the OS  to connect and interface the hardwares (keyboard, mouse etc.) with your software and you can just keep this one as it was in the template.

**Comment by JohnErnsthausen** [comment]
Dear @LeilaMousapour and Prof @smiths,

Thank you for your comments Leila. I chose to eliminate the hardware hiding module because my software is a library.

I addressed your concerns in [Commit be91b6](https://github.com/JohnErnsthausen/roc/commit/be91b6f46a3965e2e03542193e0b64a3b980cada).
