### ISSUE TITLE
SRS ready for review.

### ISSUE THREAD

**Issue by JohnErnsthausen** [JohnErnsthausen/roc#7]
Hello, Leila @LeilaMousapour and Prof. Smith @smiths. My SRS document is ready for review.

**Comment by smiths** [comment]
@JohnErnsthausen, you mean your VnV document?  :smile:  

Please create a separate issue for each reviewer to do their review.

**Comment by JohnErnsthausen** [comment]
I'm not seeing comments for my SRS and my VnV from Leila @LeilaMousapour. Perhaps I have her handle wrong or she has my handle wrong?🤷‍♂️

@smiths

**Comment by smiths** [comment]
@JohnErnsthausen, you have the correct id for @LeilaMousapour.

**Comment by smiths** [comment]
Feedback on the SRS is available in commit 24a93ae.  Please create issues as appropriate.
