### ISSUE TITLE
VnVPlan: What happens if the user misuses the program?

### ISSUE THREAD

**Issue by liziscool** [JohnErnsthausen/roc#9]
Hi @JohnErnsthausen,

So I've been thinking about the test cases and I think they actually do totally cover the scope of your program, so that is good. (I keep trying to find things that the test cases don't address but then I realize it does address them...)

So the only other concern that I can think of is what if the user misuses the inputs? Trivial stuff like if they want the length to be negative, the initial value problem is nonsense, etc? I think you might just need some test cases that ensure the program gives an error when the user makes a mistake with the inputs.

**Comment by JohnErnsthausen** [comment]
Hello @liziscool,

I added Section 5.1.1 in VnVPlan to address inputs.

[commit be14c3](https://github.com/JohnErnsthausen/roc/commit/be14c310b5156fa5f27eda508671384151908fba)

@smiths
